name: Documentation
description: Select this to document the repo
title: "Directory You Purpose to Document"
labels: ["Hacktoberfest2021", "Hacktoberfest", "new submssion", "first timer", "good first issue", 
"documentation"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Before starting please take a look at [this](https://github.com/ahampriyanshu/algo_ds_101/tree/main/DOCUMENTATION.md), [this](https://dsa.ahampriyanshu.com/DOCUMENTATION) and [this](https://dsa.ahampriyanshu.com/Data-Structures/Queue/).
  - type: input
    id: directory
    attributes:
      label: Directory
      description: Path to the readme file
      placeholder: Algorithm => Sorting => Merge-Sort => README.md
    validations:
      required: true
  - type: checkboxes
    id: language
    attributes:
      label: Things To Remember
      description: Please check the following
      options:
        - label: The content added isn't directly copied from any sources like gfg, tutorialpoint, etc. For theory, use open-source alternatives like WikiPedia.
        - label: I have used github flavoured md syntax only.
        - label: All the relative links are working.
        - label: All the absolute links are working.
        - label: I have synced-up my forked repo.
        - label: Ain't pushing from the main branch.
