name: New Submission
description: Selct this to submit new Algorithm/Data-Structure/Maths/STL/Collection
title: "Title of the submission"
labels: ["Hacktoberfest2021", "Hacktoberfest", "new submssion", "first timer", "good first issue", 
"c", "c++", "c#", "java", "javascript", "typescript", "php", "python", "ruby", "scala", "swift", "go"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing
  - type: input
    id: directory
    attributes:
      label: Submission Directory
      description: Location of the new file
      placeholder: Algorith => Sorting => Merge-Sort => Merge-Sort.ext
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Type of the submission
      options:
        - Algorithm
        - Data-Structure
        - Maths
        - STL
        - Collection
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the submission
      placeholder: A linked list is a linear collection of data elements whose ...
    validations:
      required: true
  - type: checkboxes
    id: language
    attributes:
      label: Programming Language
      description: programming language
      options:
        - label: c++
        - label: c
        - label: c#
        - label: java
        - label: python
        - label: javascript
        - label: typescript
        - label: ruby
        - label: swift
        - label: scala
        - label: go
        - label: php
